#!/bin/bash
# lacl - launch and control later
# a script to start a process as a daemon and provide the opportunity to attach to the console of this program
# open issues / todos
# - Improve stop, it can't currently wait on the processes.
#(-)Create Cleanup Command

USAGE="Usage: lacl start \$TOKEN [--stopsequence \"STRING\"] command [arg1 arg2 ...] | lacl connect \$TOKEN | lacl [stop|kill] \$TOKEN"

main() {
  WHAT="$1"; shift
  TOKEN="$1"; shift
  
  if [[ -z "$TOKEN" ||  -z "$WHAT" ]]; then
    echo "$USAGE"
    exit
  fi
  
  FIFO_NAME="/dev/shm/$TOKEN.ctl"
  LOG_FILE="/dev/shm/$TOKEN.log"
  PID_FILE="/dev/shm/$TOKEN.pid"
  
  # evaluate command
  case "$WHAT" in 
    start)
      start $@
      ;;
    connect)
      connect
      ;;
    stop)
      stop
      ;;
    kill)
      stop "--kill" 
      ;;
    *)
      echo "$USAGE"  
      ;;
  esac
}

# setup handles
setup_files() {
  exec {daemonlogfile}>"$LOG_FILE"
  exec {daemon_comm}<>"${FIFO_NAME}"
}

# prepare cleanup
cleanup() {
  exec {daemon_comm}>&-
  rm "$LOG_FILE" "$FIFO_NAME" "$PID_FILE"
}

busywait() {
  for pid in "$@"; do
    while kill -0 "$pid"; do
      sleep 0.5
    done
  done	       
}

start() {

  if [ -e "$FIFO_NAME" ]; then
    echo "Error: Token already in use (or not cleaned up correctly)"
    echo "$USAGE"
    exit -1
  fi

  # setup fifo
  mkfifo --mode=0620 "${FIFO_NAME}"
  setup_files

  (
    if [ "$1" == "--stopsequence" ]; then
      shift
      STOPSEQUENCE="$1"
      shift
    fi
    # echo $FIFO_NAME $LOG_FILE
    COMMAND=$1; shift
    if [ -z "$COMMAND" ]; then
      echo "$USAGE"
    fi
  
    # disable SIGTERM and SIGINT for the daemon process:
    if ! [ -z "$STOPSEQUENCE" ]; then
      trap "" TERM # avoid kills by systemctl
    fi
    trap "" INT # avoid kills when the interactive console is aborted
    
    # start the daemon process
    $COMMAND $@ <&${daemon_comm} >&${daemonlogfile} 2>&${daemonlogfile} &
    
    # Now get the PID of daemon, issue stop, wait for it synchronously within the signal handler and clean up afterwards -- 
    PID=$!
    echo "$PID " >>${PID_FILE}
    sync
    if ! [ -z "$STOPSEQUENCE" ]; then
      trap "echo $STOPSEQUENCE >${FIFO_NAME}; wait $PID" TERM
    else
      trap "kill -s SIGTERM $PID" TERM
    fi
    trap "" KILL # can't ignore SIGKILL, but this prevents an unecessary message on the console "lacl: line XX: $PID Killed [...]"

    # wait and clean up afterwards
    trap cleanup EXIT

    wait $PID 
  ) & 
  echo -n " $! ">${PID_FILE}
}

connect() {
  # assert fifo exists

  if ! [ -p "$FIFO_NAME" ]; then
    echo "Error: Pipe not found!"
    echo "You need to start a command for the given token first."
    echo "$USAGE"
    exit -1
  fi

  # setup_files -- should not be used.

  tail -f "$LOG_FILE" &
  local TAILPID=$!

  trap "kill $TAILPID" EXIT 
  while IFS= read -r -s -d "$(echo -ne '\0004')" -n 1 char; do
    if [[ ! -p "$FIFO_NAME" ]]; then echo "connection lost"; break; fi
    echo -ne "$char" >"${FIFO_NAME}"
  done
}

stop() {
  if ! [ -f "$PID_FILE" ]; then
    "Attention: Pid file is not present, cannot stop any processes for \"$TOKEN\"." 
    exit 0;
  fi

  if [ "$1" == "--kill" ]; then
    SIGNAL=SIGKILL
    trap "rm $LOG_FILE $FIFO_NAME $PID_FILE" EXIT # not via cleanup due to missing setup of named redirect
  else
    SIGNAL=SIGTERM
  fi

  kill -s ${SIGNAL} $(<"$PID_FILE")

  busywait $(<"$PID_FILE")
}

main $@

# ---------------------------------- development snippets ---------------------------------------------------
# $while true; do IFS= read -r -n 1 line; echo "$line"; done <&${testfifo} &
#[1] 1692
# $while IFS= read -r -n1 char; do echo -n "$char" > test; done

